### ISSUE TITLE
explore router statefulset

### ISSUE THREAD

**Issue by qrkourier** [openziti/helm-charts#258]

**Comment by dariuszSki** [comment]
Issue  trying to solve: 
Pass List of tokens to a set that can have more than one replica. One unique token to be available at the deployment  to register each router separately. 
Why stateful set: it maintains the stable pod identity, i.e name is created based on the metadata/name plus -0, -1, etc. The theses  were to create ENV VAR that varies with its name and pins the jwt token to it. i.e.
```
env:
          - name: M_NAME
            valueFrom:
              fieldRef:
                fieldPath: "metadata.name"
          - name: ZITI_ENROLL_TOKEN
            valueFrom:
              secretKeyRef:
                name: ziti-router-identities
                key: $M_NAME
       
```
 Unfortunately, you can only read another variable after it is deployed, so this can be used to dynamically set the reference to a token secret.   But if the entry script is altered and is able to read ZITI_ENROLL_TOKEN, then retrieve that token from the secrets store by using its name as a key. Maybe?

Another way perhaps is to use Operator Pattern and read/even create the token directly on the Ziti Controller  at run time and patch the statefulset with new token EBV VAR everytime a new container comes up. I did and continue to explore this avenue, but it is tricky. Most likely one would need to create the configmap/secret and patch that instead, this option still to be verified though. Some notes on this:
SetupWithManger Reconciler would look something like this. Would need to watch the pods, since new CR would not be the owner of them. Here is the code to my poc on that. https://github.com/dariuszSki/ziti-operator 
```
func (r *ZitiRouterReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&zitiv1alpha1.ZitiRouter{}). // Watch the primary resource
		Owns(&appsv1.StatefulSet{}).     // Watch the secondary resource (Statefulset)
		Owns(&corev1.ConfigMap{}).       // Watch the secondary resource (ConfigMap)
		Watches(&corev1.Pod{}, &handler.EnqueueRequestForObject{}).
		Complete(r)
}
```

Last thought on this, if we are going down the road of Operator Pattern,  then perhaps it makes more sense to just manage more than one single deployments and token env var is created at the time of the deployment details rendering not at run time . Options [art of CR would be for example for users to choose from:
- tproxy mode, operator would spin up as many single replica deployments they are nodes, i.e. daemonset
- proxy/host modes,  operator would spin up only two copies for redundancy.
