### ISSUE TITLE
.github/workflows/deploy.yml is never triggered

### ISSUE THREAD

**Issue by qrkourier** [openziti/helm-charts#3]
```yaml
name: Deploy

on:
  push:
    branches:
      - master
```

The only trigger is a push to branch `master` which does not exist.
