### ISSUE TITLE
Allow configuration of Liveness and Readiness timeouts for router

### ISSUE THREAD

**Issue by philippsteinberg** [openziti/helm-charts#340]
Hi,

we noticed some problems with the default timeout of 1 second for the liveness and readiness checks in our cluster.
When we have higher load on our cluster it can happen that some calls take more then the default timeout of 1 second.

We now changes the values manuel to 5 seconds and with this everything works fine.

It would be nice to make the probe thresholds and timeouts configurable via the helm chart.
like this:

```
probe:
  active: true
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5
```

If it makes sense to make it more configurable like also update to probe command of use different values for readiness and lifeness I don't know.

What do you you think of this idea?

BR
Philipp
