### ISSUE TITLE
console chart: better support for cert-manager

### ISSUE THREAD

**Issue by qrkourier** [openziti/helm-charts#65]
The console chart sets up server TLS if a secret name is provided and assumes the secret is managed by the issuer. Deployment will fail if the named secret doesn't exist. If secretName isn't defined and ingress is enabled the Kubernetes Ingress Controller Fake Certificate is bound to the service.

It's already possible to configure verifiable server cert if the cluster has a Let's Encrypt cluster issuer. This is accomplished by adding annotations to the ingress like this Helm values.yaml example:

```yaml
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: ${cluster_issuer}
  advertisedHost: ${console_domain_name}.${domain_name}
  tlsSecret: ${console_release}-tls-secret
```

Add support for cert-manager. We can do this by adding a value `ingress.cluster-issuer`. The value is used to annotate the ingress:

```yaml
metadata:
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.cluster-issuer }}
```

If a cluster issuer with that name doesn't exist, one is created. This way, you'll get an unverifiable cert from the designated issuer at the very least, and if you already have a ClusterIssuer set up with ACME then it simplifies the needed Helm values.
