### ISSUE TITLE
move non-variable values to named templates

### ISSUE THREAD

**Issue by qrkourier** [openziti/helm-charts#90]
Some Helm chart values should have been [named templates](https://helm.sh/docs/chart_template_guide/named_templates/) instead of values. The difference is that values are variables that you can set when you create a release, i.e. install the chart, whereas named templates are set automatically.

For example, in the ziti-controller chart, there are a bunch of variables/values like these that never need to be set:

```yaml
# -- a directory included in the init and run containers' executable search path
execMountDir:   /usr/local/bin   # read-only mountpoint for executables (must be in image's executable search PATH) 
# -- exec by init container
initScriptFile: ziti-controller-init.bash
# -- admin profile script file
zitiLoginScript: zitiLogin
# -- ziti shell rc mountpoint where zitirc.bash is projected
zitiShellProfileDir: /etc/profile.d
# -- ziti shell rc filename
zitiShellProfileSript: ziti-profile.bash
# -- read-only mountpoint where configFile and various read-only identity dirs are projected
configMountDir: /etc/ziti
# -- filename of the controller configuration file
configFile:     ziti-controller.yaml
# -- writeable mountpoint where the controller will create dbFile during init
dataMountDir:   /persistent
# -- name of the BoltDB file
dbFile:         ctrl.db
# -- read-only mountpoint for run container to read the ctrl plane trust bundle created during init
ctrlPlaneCaDir: ctrl-plane-cas
# -- filename of the ctrl plane trust bundle
ctrlPlaneCasFile: ctrl-plane-cas.crt
```

These can become named templates because the chart needs to use the value in multiple places, but isn't not all that valuable to be able to set an alternative value when the chart is installed. As a result, these are cluttering up the values.yaml file and the README that documents these.

Here's an example of how it should be done:

Add named templates to the file "templates/_helpers.tpl" like this:

```go
{{- define "ziti-controller.ctrlPlaneCasFile" -}}
ctrl-plane-cas.crt
{{- end }}
```

Then, in any template that references the old value, replace:

```go
{{ .Values.ctrlPlaneCasFile }}
```

with

```go
{{ include "ziti-controller.ctrlPlaneCasFile" . }}
```

Then, for each value that you convert to a named template, you can remove its default value and documentation comment from the file "values.yaml."

When you push your branch to GitHub the documentation README will be automatically generated and you'll see the default values were removed by the automation.
