### ISSUE TITLE
configmap "ziti-controller-ctrl-plane-cas" not found in ziti-controller-0.2.6

### ISSUE THREAD

**Issue by sa-ChristianAnton** [openziti/helm-charts#95]
After upgrading ziti-controller from 0.2.4 to 0.2.6, the ziti-controller pod did not start up:

```
  Warning  FailedMount  32s (x8 over 95s)  kubelet            MountVolume.SetUp failed for volume "ziti-controller-ctrl-plane-cas" : configmap "ziti-controller-ctrl-plane-cas" not found
```

Reason was that the "Bundle" object created with trust-manager had the following "target" configuration:
```
  target:
    configMap:
      key: ctrl-plane-cas.crt
    namespaceSelector:
      matchLabels:
        openziti.io/namespace: enabled
```

...when no namespace was labeled with this label/value pair. I manually, as a workaround did this:

```
kubectl label ns openziti openziti.io/namespace=enabled
```

Than the configmap was created immediately, and ziti-router started just fine.

As a solution for this, should the values.yaml be changed to contain something like this?
```
trust-manager:
  # -- install the trust-manager subchart to provide CRD Bundle
  enabled: false
  app:
    trust:
      # -- trust-manager needs to be configured to trust the namespace in which
      # the controller is deployed so that it will create the Bundle resource
      # for the ctrl plane trust bundle
      namespaceSelector:
        kubernetes.io/metadata.name: openziti
```

and template this into the currently hardcoded section of [templates/ca-bundle.yaml](https://github.com/openziti/helm-charts/blob/d4a236ae6024bedcfc732ccfdc1ab240f213a327/charts/ziti-controller/templates/ca-bundle.yaml#L47)? Currently, in ca-bundle.yaml there is the label selector hardcoded, and the values' `trust-manager.app.trust.namespace` is not being used anywhere in the templates. Seems it has been left over in one of the latest commits.
